spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true # 启用监控页面
        url-pattern: /druid/* # 监控页面访问路径
        login-username: admin # 监控页面登录用户名
        login-password: 123456 # 监控页面登录密码
        allow: 127.0.0.1 # 白名单（不配置则允许所有访问）
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initialSize: 5 # 初始化连接数
            minIdle: 5 # 最小空闲连接池数量
            maxActive: 30 # 最大连接池数量
            maxWait: -1 # 获取连接时最大等待时间（毫秒）
            filters: stat,wall # 连接池监控配置（stat：统计监控信息；wall：SQL防火墙）
        test:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initialSize: 5 # 初始化连接数
            minIdle: 5 # 最小空闲连接池数量
            maxActive: 30 # 最大连接池数量
            maxWait: -1 # 获取连接时最大等待时间（毫秒）
            filters: stat,wall # 连接池监控配置（stat：统计监控信息；wall：SQL防火墙）
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  file:
    path: D:/logs/simpleFramework
  level:
    root: info
    org.springframework: info
